version: '2'

services:
  web:
    container_name: whatsapp_load_balance
    build: .
    ports:
      - "4001:3000"
    environment:
      - DATABASE_URL="mongodb://database:27017/whatsapp_load_balance"
  
  database:
    container_name: database
    image: mongo
    volumes:
      - mongo:/data/db
volumes:
  volume-name: mongo